# Generated by Django 3.1.4 on 2020-12-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201220_1147'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subtask',
            name='tasks_subta_parent__e124cb_idx',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='parent_uuid',
            new_name='parent',
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['child_uuid'], name='tasks_subta_child_u_a2f3ab_idx'),
        ),
    ]
