# Generated by Django 3.1.4 on 2020-12-20 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201220_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.task'),
        ),
    ]
